from PyQt5 import QtWidgets, uic # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
# lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
from PyQt5 import QtCore # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
# lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
import sys # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
# lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
qtcreator_file = "bmi.ui" # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
Ui_PersegiWindow, QtBaseClass = uic.loadUiType(qtcreator_file) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
# lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
class MyPersegiWindow(QtWidgets.QMainWindow, Ui_PersegiWindow): # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    def __init__(self): # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        QtWidgets.QMainWindow.__init__(self) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        Ui_PersegiWindow.__init__(self) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        self.setWindowModality(QtCore.Qt.ApplicationModal) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        self.setupUi(self)
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        self.btnHitung.clicked.connect(self.hitung)
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
# lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    def hitung(self):
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        berat = float(self.txtBerat.text()) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        tinggi = float(self.txtTinggi.text()) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        a = tinggi / 100 ** 2 # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        b = berat / a # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        self.txtBmi.setText(str(b)) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
        # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
# lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
if __name__ == "__main__": # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    app = QtWidgets.QApplication(sys.argv) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    persegi = MyPersegiWindow() # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    persegi.show() # Show in normal mode # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    sys.exit(app.exec_()) # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 
    # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur # lieur 